apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-infra
  namespace: kube-system
spec:
  dependsOn:
    - name: cilium
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./deploy/cilium
  interval: 10m
  timeout: 1m
  prune: true
