apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homeassistant
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant
      secret:
        name: cnpg-homeassistant
  managed:
    roles:
    - name: homeassistant
      login: true
      passwordSecret:
        name: homeassistant-database
