apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
      namespace: kube-system
  path: ./deploy/flux-system
  interval: 1m
  prune: true
  force: true
  wait: true
