apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- sources
- apps
patches:
- target:
    kind: Kustomization
    name: flux-system
  patch: |
    - op: add
      path: /spec/path
      value: ./deploy/flux-system
    - op: add
      path: /spec/decryption
      value:
        provider: sops
        secretRef:
          name: sops-age
- target:
    kind: GitRepository
    name: flux-system
  patch: |
    - op: replace
      path: /spec/ref/branch
      value: feat/homeassistant

- target:
    kind: ServiceAccount
    name: source-controller
  patch: |
    - op: add
      path: /imagePullSecrets
      value:
        - name: registry-auth
