apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secrets/
- apps/
patches:
- target:
    kind: Namespace
  patch: |
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1audit
      value: restricted
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1enforce
      value: restricted
    - op: add
      path: /metadata/labels/pod-security.kubernetes.io~1warn
      value: restricted

- target:
    kind: Kustomization
    name: flux-system
  patch: |
    - op: add
      path: /spec/decryption
      value:
        provider: sops
        secretRef:
          name: sops-age

    - op: replace
      path: /ref/branch
      value: feat/homeassistant

- target:
    kind: ServiceAccount
    name: source-controller
  patch: |
    - op: add
      path: /imagePullSecrets
      value:
        - name: ghcr-auth
