apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- kustomization/
patches:
- target:
    kind: Kustomization
    name: flux-system
  patch: |
    - op: add
      path: /spec/force
      value: true

- target:
    kind: Deployment
  patch: |
    - op: add
      path: /metadata/annotations/kustomize.toolkit.fluxcd.io~1ssa
      value: Override
