apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    metadata:
      name: all
    spec:
      decryption:
        provider: sops
        secretRef:
          name: sops-keys
  target:
    kind: Kustomization
    name: flux-system