apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secret.sops-age.yaml
- secret.ghcr-auth.yaml
- apps/
patches:
- target:
    kind: Kustomization
    name: flux-system
  patch: |
    - op: add
      path: /spec/decryption
      value:
        provider: sops
        secretRef:
          name: sops-age

- target:
    kind: ServiceAccount
    name: source-controller
  patch: |
    - op: add
      path: /imagePullSecrets
      value:
        - name: ghcr-auth
