apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:eGUR3Z30wpfeMajQ0si/VXxoplwA3qF9dbCYVxDqdiqzeu8+V97ucjeqdGk6kI/9/1ND/gid1aykHcwOsJ84MG4EwerBPyPj/Z4nntl/cO/TgD2F5rB2P/e8QtbR8xuvF7AdHn7fU5ycbXJ9T/2KyKboqux1jvodEZL5KiD26XOkH9+peMDoOMGZr7Q5JKGG9zd22Gr0ENrUTT3n7wHUxl5aZyumkeKP9V2Ubb4DnwKV,iv:+ikPpTrT4Ywy7iLK4jPck4jn3MybvadTCgjrFdP8QOw=,tag:62tyjPTrnJ9N1d/Kwrm22w==,type:str]
sops:
    age:
        - recipient: age1asrypfk4rkp8fkldqkrp6snhcxmanwtykc8xtzhd4n43f7zzkppst934ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSDZYMUJGemlzNnNqTDBa
            eWJoM0VJZmJuVVJxQlhrZkZLYlpMcDhtM0NnCjhDZmRlbTRadnI2VFd3NmlhZTNz
            WjNNMGJHMWg4M2VIZ2tVNkdDbGhvdlEKLS0tIFNyVEVYNlVsN1lUTWxPTmt4QVg5
            VGVjUW94VXhmd0tCMmU0dUdOakFlMlkKJOyUhl1UsgbJsaoBICuCGJ6ZqdrjQQL9
            xPTfsWAAH0Ty5EmSfduX+lp/lu0JKnUX2JLu7OXxT5iYEpLh3DtKTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T21:00:59Z"
    mac: ENC[AES256_GCM,data:Up42F+rwQ04SQYWjf3/x7/9bRS+2t/XRMnrUwNwFRIjjGY6BHnZxrf0WbAIQcmhSpNYESpxbLPsM62yjf3Wcvqu7SnHpDlliTIBiTBaLchedPMQAJ455hAlNJ4nqIU3lfrulho6wfqjqypnQBZru8rtq04Vk2P4pXF3PSOTJ2as=,iv:ewEhBnZRO9awh672bJ5IL746eXj5dqcFwcXgZFoLBsE=,tag:gtmseaRwvnACFkue2klSCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
