apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: akri
      chart: akri
      version: 0.13.8
  targetNamespace: akri
  releaseName: akri
  values:
    kubernetesDistro: k8s
    udev:
      discovery:
        enabled: true
