apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 1m
  url: https://coredns.github.io/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: coredns
      version: 1.38.1
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 20m
        memory: 32Mi
      requests:
        cpu: 20m
        memory: 32Mi
    service:
      clusterIP: 10.43.0.10
    serviceAccount:
      create: true
