apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: coredns
      version: '1.37.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: coredns
  interval: 1m0s
  releaseName: coredns
  targetNamespace: kube-system
  values:
    replicaCount: 1
    service:
      clusterIP: 10.96.0.10
    serviceAccount:
      create: true
