repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
        files: ^terraform/.*

      - id: terraform_validate
        files: ^terraform/.*

      - id: terragrunt_fmt
        files: ^terragrunt/.*

      - id: terragrunt_validate
        files: ^terragrunt/live/.*/

      - id: terragrunt_validate_inputs
        files: ^terragrunt/live/.*/

      - id: terragrunt_providers_lock
        files: ^terragrunt/live/.*/