repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.101.0
  hooks:
  - id: terraform_fmt
    files: ^modules/.*

  - id: terragrunt_fmt
    files: ^infra/.*

  - id: terragrunt_validate
    files: ^infra/live/.*/terragrunt\.hcl$

  - id: terragrunt_validate_inputs
    files: ^infra/live/.*/terragrunt\.hcl$

  - id: terragrunt_providers_lock
    files: ^infra/live/.*/terragrunt\.hcl$
    args:
      - --args=-platform=linux_amd64
      - --args=-platform=darwin_arm64
