repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_fmt
      # TODO: make this work
      #- id: terraform_providers_lock
      - id: terraform_docs
      - id: terragrunt_fmt
      # TODO: make this work
      #- id: terragrunt_providers_lock