apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1m
  url: https://headlamp-k8s.github.io/headlamp
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 1m
  chart:
    spec:
      chart: headlamp
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
