apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  hostnames:
    - headlamp
  parentRefs:
    - name: cilium-gateway
      namespace: cilium-system
  rules:
    - backendRefs:
        - name: headlamp
          port: 80
