apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: tank
    pvcTemplate:
      volumeName: local-pv-24158c21
  superuserSecret:
    name: database-superuser
  bootstrap:
    initdb:
      database: home-assistant
      owner: home-assistant
      encoding: utf8
