apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: home-assistant
      owner: home-assistant
