apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: home-assistant-database
spec:
  refreshInterval: 5m
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: 1password
  selector:
    secret:
      name: home-assistant-database-app
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: HomeAssistant Database
        property: password
    metadata:
      apiVersion: kubernetes.external-secrets.io/v1alpha1
      kind: PushSecretMetadata
      spec:
        tags:
        - tag1
