apiVersion: v1
kind: Secret
metadata:
    name: database-superuser
stringData:
    username: ENC[AES256_GCM,data:rIycXwrYYMk=,iv:Hq9yIOd+RbBPqhj/opf50fESisPthl2eUXVjIApnpTo=,tag:CmGlkvtdGT3qTmIGDelr0Q==,type:str]
    password: ENC[AES256_GCM,data:QuvHsbULUMAGRFMwv4U8VLJ2iFu83XikCyR9LqTdMXU=,iv:qFu3GiPZ7Qrrd7r0OzcKRhD3OOKTXwgJE9jPpZExDW0=,tag:jyZVzPPc8tyNv6Hn3iFolg==,type:str]
sops:
    age:
        - recipient: age1asrypfk4rkp8fkldqkrp6snhcxmanwtykc8xtzhd4n43f7zzkppst934ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYkpTR3FDMW1nVzdBWkVK
            REh3RFdGMTZFdk1PUGh6UERBclQ2RFU1M3lVCks1V1B2eE0rZ3k3L3ZzTk5ZTUxD
            OGhjTnRrSmRZSDR2eWFYMlFFbTlKVncKLS0tIE43emFEeUY5MUdGOHpJTkNCWkFX
            YXVNQ2VQSkFNT1BuTE9WZ25uVmpWaVkK+qoU15bKQkzWt6+BCxHEQmPF8o1IVfCd
            2zRL9N/L9SIbGSaoWx4zewnHvEoCXLLRmrfyNhHPNRZdydbnmGmEQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T10:00:19Z"
    mac: ENC[AES256_GCM,data:AnZ3ch0ImW7sFxhUcNV+JCSB6TUVZAd6dvf9KJB+7qceF5wVJhk88ydjdpfsnvslXGAY7D/pEVtAhBrz7nOclv4akw6bc/1XYo6VbymUXpPisgHv6C2uflKTYJnWiRyFGhq006P8/MO5vW1zsP8rcfUzcTLHrhILD+ywzaX+h5U=,iv:SARNiNiev7Pgqy5PkNFPLq8rIXGszXq1/n2ckUj4TMY=,tag:wnXDMuMo+IJ+9jaM6iGKUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
