apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 10m
  suspend: true # TODO: remove
  targetNamespace: openebs
  releaseName: openebs
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: openebs
      chart: openebs
      version: 4.3.3
  values:
    zfs-localpv:
      zfsNode:
        encrKeysDir: /var/openebs-zfs

    engines:
      local:
        lvm:
          enabled: false
      replicated:
        mayastor:
          enabled: false

    alloy:
      enabled: false

    loki:
      enabled: false

  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: DaemonSet
          name: openebs-zfs-localpv-node
        # language=yaml
        patch: |
          - op: remove
            path: /spec/template/spec/containers/1/volumeMounts/5
          - op: remove
            path: /spec/template/spec/volumes/6
