apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Kustomization
    name: flux-system
  patch: |-
    - op: add
      path: /spec/dependsOn
      value:
        - name: cilium
          namespace: kube-system

