apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    policy: sync
    triggerLoopOnEvent: true
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
    sources:
      - service
      - gateway-httproute
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.0
        env:
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: password
        securityContext:
          readOnlyRootFilesystem: true
