apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  interval: 10m
  chart:
    spec:
      chart: ${chart_name}
      version: ${chart_version}
      sourceRef:
        kind: HelmRepository
        name: ${name}
      interval: 30m
  values:
    replicaCount: 1
    serviceAccount:
      create: true
    service:
      ipFamilyPolicy: RequireDualStack
      clusterIP: ${service_ips[0]}
      clusterIPs:
      %{~ for ip in service_ips ~}
      - ${ip}
      %{~endfor}
