apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan
      labels:
        app: home-assistant
    spec:
      serviceAccountName: home-assistant
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2025.12.4
        env:
        - name: TZ
          value: Europe/Berlin
        - name: RECORDER_DB_URI
          valueFrom:
            secretKeyRef:
              name: database-app
              key: fqdn-uri
        ports:
        - name: http
          containerPort: 8123
        - name: homekit
          containerPort: 51827
        volumeMounts:
        - name: config
          mountPath: /config
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: home-assistant
