apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
spec:
  hostnames:
  - home-assistant-new
  parentRefs:
    - name: home
      namespace: gateways
  rules:
    - backendRefs:
        - name: home-assistant
          port: 8123
