apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/networking/external-dns
  interval: 10m
  prune: true
  dependsOn:
  - name: coredns
  - name: external-secrets
