apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: external-dns
      chart: external-dns
      version: 1.19.0
      interval: 30m
  install:
    createNamespace: true
  targetNamespace: external-dns
  releaseName: external-dns
  values:
    triggerLoopOnEvent: true
    policy: sync

    sources:
      - gateway-httproute

    provider:
      name: webhook

      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v9.1.0

        env:
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-adguard
                key: password

        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5

        readinessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
