apiVersion: v1
kind: Secret
metadata:
    name: external-dns-adguard
    namespace: external-dns
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:Bw3VPcORNSmBZH9HycEElQRGMRaPHa8=,iv:NkckkhgiZhyoNynd/yyjtsBqU6xYb7rV7lIHz9wTHBE=,tag:EdukqMEjYkifYeE0f2j7lA==,type:str]
    user: ENC[AES256_GCM,data:v5nIBnv7oGzuumok,iv:u7DJG7MFnhu4Z4r+8hUb77UaGro6Xoz59OYzUfwIcaE=,tag:hzgJwLmkQU27L6Tb04PLtg==,type:str]
    password: ENC[AES256_GCM,data:W/KQj/TTsP1IuL09kdZMjN5OxkVNrMVAw/auvQepYf4=,iv:Yjj/pUm/FnIEGiMXCF5DVv0gPxE7kWPbOeM+MHM0ngg=,tag:+K5S3eQb6kxxEwazO2Z2Yw==,type:str]
sops:
    age:
        - recipient: age1asrypfk4rkp8fkldqkrp6snhcxmanwtykc8xtzhd4n43f7zzkppst934ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQTZvQzJ0dkpPVkNvbExh
            M1VwT1NrdERWdWd0Q002ZXc4a3pwNGgxYmdFCnd1QkZWZDB0dmFEMWZoMTZZU25X
            c0NibkNnRkw5TFdyZ1U2blZiSWFrZHMKLS0tIFhReDZyK0hMbi9KZ1JKNDVPYUUw
            SWF5VGhoSkthaW1TUWE4Q1MyaUt3aU0KoYSLvGDD/eVKCBqNGODPU6trKoJQTCAm
            BQgwpi43+FpYXQ3vC0j6e5jDGuguxBvW4zfwTKSo02UWnWLKmxRJcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T00:14:48Z"
    mac: ENC[AES256_GCM,data:89HIk2s1JsKTs/SMT8Eu4DZ+R4DD1uL+UNUZu1rZ0NCvIiZQIPZEh352VC+UD5bndzKRtQtgkHbei0XxKqjA+hl5MeAjJtMIS+Hnt2Ma6/Po7BPpm7vHNtcr+VLH494B9TkLed3aXaJK9kSkduHvr9t8yhDJd/+GzVlr0VAIjs0=,iv:1EH2GNmKvEk1Sx3/KCM4dZZ+znd8l0tDe1xDLj2LSoI=,tag:pkMtWWtj734V/H8XuqZgqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
