apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: cilium
      chart: cilium
      version: 1.18.2
      interval: 30m
  targetNamespace: kube-system
  values:
    cluster:
      name: knecht

    rollOutCiliumPods: true

    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true

    routingMode: native
    autoDirectNodeRoutes: true
    enableIPv4Masquerade: false
    enableIPv6Masquerade: false

    ipv4:
      enabled: true
    ipv6:
      enabled: true

    ipam:
      mode: multi-pool

    bpf:
      lbExternalClusterIP: true

    bgpControlPlane:
      enabled: true

    hubble:
      relay:
        enabled: true
      ui:
        enabled: true

    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true

    operator:
      replicas: 1
      rollOutPods: true

    envoy:
      rollOutPods: true

    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false

    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - DAC_OVERRIDE
        - FOWNER
        - IPC_LOCK
        - KILL
        - NET_ADMIN
        - NET_RAW
        - SETGID
        - SETUID
        - SYS_ADMIN
        - SYS_RESOURCE
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

