apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: cnpg-system
  releaseName: cloudnative-pg
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: cloudnative-pg
      chart: cloudnative-pg
      version: 0.26.1
