sops_agekey: ENC[AES256_GCM,data:agydK/HSU2TRsDtNkkZH9mHJWogTCOBy+xraMH76V2o4L8kOBEPO/7BzsaD9IuibOOqVhwcGd7yFeSgg59bqP0NtbzMOJxcKxsI=,iv:EXKkApRV+2iOsClWBHRoi6b7TQrPsRlGZyiK8+1AJf0=,tag:D8j9b0wYbaOJuUvf/YZ28Q==,type:str]
registry_auth:
    ghcr.io:
        username: ENC[AES256_GCM,data:nyLfX2CASiY=,iv:inGjxna1sE8z1diRSNkqeJpKNcss18q3dnQn1gjaRtI=,tag:CFcJdmAq8oNKR/zKmqSlWQ==,type:str]
        password: ENC[AES256_GCM,data:1RwCSE/UWKoEWvg0Jz1zAMrMRjazOnsmgTvMwYW/lqazJXZTKoE7Zw==,iv:rHEN8FX9w7dKHxODQHB4+Cpm607Qr3PVjF+1yeaJ4J0=,tag:fDilcYdxwQFouUFdA7B4DQ==,type:str]
sops:
    age:
        - recipient: age1asrypfk4rkp8fkldqkrp6snhcxmanwtykc8xtzhd4n43f7zzkppst934ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUXNIY2NOc2FjeUZlZXVq
            aUdMOWNRVGlPU3poM1NoL1RoS1ZQRmllaURFCnBPOWtVNmVyQXFaRUhjeUZqTDV3
            N2xtcW8wc21kekpJRjQzaXpoVEJjbVkKLS0tIDNqckJtWDFTZ2Y0UXoxZ3dlZVBp
            Wk0wOC8rbmlZQnh2b051UzJIZzJvTk0KEN/LkHkRjPF4j98SWQm8sP4CbO93Ytln
            W/SV8jeExobrMaN+qopBjK0rFNql2x9ZkuSThTkWe61VDLjc3D+Bhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-13T07:31:17Z"
    mac: ENC[AES256_GCM,data:FdHUAietyGH4ci4KUZs61csaAnH/erope1LHUySHAh2Ur9/6a3nERA4nfIcn72d6hrh4ZBSIVL9M39ScTyO8pcqEHTw0PuviVuVqIO16JmYBxepHi+lmrT2PdC+70xudNjRFRMDvNdwARo7ljgg0cRtw/vMZsWEVtKQxInIY1TA=,iv:aT5uuX/tW0/FU3OmFVca9I/qN5BzWKCInvSxAQE4kc0=,tag:r5v45z4Kq1gSeYvwl3wOsA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
