apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cilium/chart
  interval: 10m
  timeout: 1m
  prune: true
  wait: false
  dependsOn:
  - name: gateway-api
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cilium-operator
    namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-bgp
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cilium/bgp
  interval: 10m
  prune: true
  dependsOn:
  - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-ip-pools
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/cilium/ip-pools
  interval: 10m
  prune: true
  dependsOn:
  - name: cilium
