apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/gateway
  interval: 10m
  prune: true
  dependsOn:
  - name: gateway-api
  - name: cilium
