apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: coredns
      chart: coredns
      version: 1.45.0
      interval: 30m
  targetNamespace: kube-system
  releaseName: coredns
  values:
    replicaCount: 1
    serviceAccount:
      create: true
    service:
      ipFamilyPolicy: RequireDualStack
      clusterIP: 172.17.0.10
      clusterIPs:
      - 172.17.0.10
      - fd5d:feeb:a195::a
