sops_age_key: ENC[AES256_GCM,data:ATI9Mj+BgSdtD1SwZm6s3z1EFeKBaTZuGtn/AnQ9O8aB/WgOQGfuRF25Ao7/j1DAZTIsooyUXudHiMRMNE8Ly4KjLWJWnJxSObI=,iv:OE/hKxBLQr3ppp0VY6ACLyKXHg5mqJJt/MMW7GQSTBY=,tag:sfw/ZEtHu3PJXKKj+FbTYg==,type:str]
#ENC[AES256_GCM,data:HOR+dYZ/Eww=,iv:yw1CF7LCigKhE6IpwuSfPkHjLg1Ros3fCoWTbCeWhGQ=,tag:fchnD16ZJZq6lP0pd0/j3g==,type:comment]
proxmox_endpoint: ENC[AES256_GCM,data:7cTK8BD47kafbD0Q17vftWFVgAI=,iv:z5Bd1gr3Po7fIAMzpgwrzy41/qmq6xvTgbG1SaZyBuk=,tag:acfSACqd1yin0mDRaRjWlA==,type:str]
proxmox_insecure: ENC[AES256_GCM,data:nFTMpQ==,iv:lwsEl9k9mXXdYhvjHujPf8LPnvQuZJTYUgsetm89CQo=,tag:x2ogwX0rYKhqHyEXge/UCw==,type:bool]
proxmox_token_id: ENC[AES256_GCM,data:Ay3IlLXDF0nvLiZnZpJCIj21UP3LH8w=,iv:LwzCfrJZhzHgjreMjarcpNoYZZOi+sjFbvUA363NIEk=,tag:MJK2f/r6kqkHMB6Tx4KYSg==,type:str]
proxmox_secret: ENC[AES256_GCM,data:pSZTHHtr30rZdKeTst97ZZev2SLxKBgFK57tJOYvSGBE8XeR,iv:/kcwSyYvevGdwlpUZYNtylN56lthS3jSr//I5S2dAvM=,tag:kGCQwrnnKGXIl5CUaEIFRg==,type:str]
#ENC[AES256_GCM,data:J9YX0c8/kKA=,iv:Vg/y3X52xMgg5+d1PjquBAFyP2arfn3Qn53JC0kanB0=,tag:PuL6MH4nURtfjNJFALONJw==,type:comment]
openwrt_username: ENC[AES256_GCM,data:1jJszg==,iv:cHF4vK+OJTOwvfc1O1lvoJvRuqYvH3hGw6C3OiVAoJc=,tag:OP/tWD6AV32jXCPyQm8+xg==,type:str]
openwrt_password: ENC[AES256_GCM,data:jOm5FSVQg1go4clbIi0U,iv:6+QxG/pUk6kQvlLiN5We8HrC1ISsOSX2SVrgM3HjrOI=,tag:5/ZRsjoDWIkjEFLlINFDjw==,type:str]
openwrt_host: ENC[AES256_GCM,data:XWJDSPyp,iv:Z3IUsenoEUBIh8gRFIBSI97z1hZZ4zblXLUhvZsz7iY=,tag:86Bbn1tgXe6MKy5xFH9JTg==,type:str]
sops:
    lastmodified: "2025-08-23T11:09:18Z"
    mac: ENC[AES256_GCM,data:Wag8W3WatuHMsFbHjNn68FoOEVNfcFk27Ig7oBJYXJkIyDrauCR0bAi4YaDaPROeKZI/awWpu09P4Ess9Sq8SbU6xRajWpTskKr2jjcWkQI+mPA54IiX2YQ5GZ9WPzAuUidt1pRY85uQPEIs6bXm3i+g2UuLxMjPcDt43RGFtl4=,iv:QYgNHvJ2+Mpj4SgDFRK0YXtgz46NQW1BgAGDdlUWLyQ=,tag:9BwzHb4N1CypwhfoxLom8w==,type:str]
    pgp:
        - created_at: "2025-05-24T02:50:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7hvRwmznHI/AQ//dVvWtD/f1xYKG0WFADF40vxEvQNR5OD4737z2pfMztcL
            AF76KvpVTMYyfaui1QNCck+MDMSRzihm+6XFJ1/fDEdUboBm0KBjJSGVBY0OzV9b
            iWtg465TCtrJFR0SebVeczT5QGSLm7Kmu0r0OTkVsAFYzZ0TH/DI6VqI5GoUu1O0
            qgYfMt0cDaoaQzaX6fbRYXgsAWQ6DDi3+DYl8VknpNpZS2FljDtye2dxEUMfF0aK
            FR9iRWID7IrFXaJzti/FoQz4g808qxeP7uSDM4qDRAHUo9gzO3GY4yRpcNBaACMN
            zosGe0moETt94zEp2PfR1AxPPDk081j4JWEMvjQzVZAPLQZHvAOTEb3JUn3za6aO
            +e/Sry3e0w1TrjZffFsDn0xaD80/ddlSIxPUCspFUwfU1mZZe+eRJcHiU/k2+fUr
            ejKTjOgla4Uhcnj1t6DYCbW+lpuSfPNaczmg8GMMFdSGSRalYm4cP/98sukbq1mu
            jUsbigzDQUcsE8/S0lknvij6jFs/POve3E3qiftYrXlw29prKNpSLlHdQwGbFpVo
            bkt3cWI2c50lOwSW+cwqMr02/1JixZexDYNrIkxl0DRGDLN9x6u9s/M/yekJmU0a
            ch9a8igL/pGccPE+pionShj+rkSYjXRHlDbB67MHSi10pP3qk3M7o7UINtq/RCrS
            XAFUUY5epe962h1wvfW8nv9rqH5X7Qxgsdv9F6m/ZsJEI9eGIHFbS1orzdHGQqb9
            LgqtRjo7cGxTfUjptSUQ6jc8ByxhBHxXbE2l3/PVTq6589tbVBDVEqlDFtfq
            =r5r3
            -----END PGP MESSAGE-----
          fp: DE42D032860CBFC10697E596C5222AA4CD5F9F36
    unencrypted_suffix: _unencrypted
    version: 3.10.2
