apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: ./deploy/cloudnative-pg/base
  interval: 10m
  prune: true
