apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: metrics-server
      chart: metrics-server
      version: 3.13.0
      interval: 30m
  targetNamespace: kube-system
  releaseName: metrics-server
  values:
    args:
    - --kubelet-insecure-tls
