apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cilium/chart/flux-kustomization.yaml
- cilium/bgp/flux-kustomization.yaml
- cilium/ip-pools/flux-kustomization.yaml
- coredns/flux-kustomization.yaml
- gateways/flux-kustomization.yaml
- external-dns/flux-kustomization.yaml
