apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-crds
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: external-secrets
  path: ./config/crds/bases
  interval: 30m
  prune: true
