apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: external-secrets
      chart: external-secrets
      version: 0.20.3
  targetNamespace: external-secrets
  releaseName: external-secrets
