apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  namespace: gateway
  name: cilium
spec:
  gatewayClassName: cilium
  infrastructure:
    labels:
      bgp: "true"
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
