apiVersion: ENC[AES256_GCM,data:2l0=,iv:19qbzkgkJOvDTh/XJHDOC1eDwzTWOnNJYWmEoiwKt0E=,tag:D4tWab57Xwdf8yT9v+q1wA==,type:str]
kind: ENC[AES256_GCM,data:YRLpfFOZ,iv:AiRtn+6X/gZdRBmmGqiJbn16eHFCGKBZcv3vDFQDuic=,tag:V/Lkr1q1YhkH04SL6liiDw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9lLE1Fds,iv:xQLgnloQjYTyPB4fv1f01nmrGyn+TsDdQw2vr1z9H8w=,tag:Fke5kXWFaW6uFFcE+1i2eA==,type:str]
    namespace: ENC[AES256_GCM,data:+UR6ci4ZDKLV9FA=,iv:8vwlfSfqchrHVPBGZqdi2UKZtkl2AwNquRK+YGPGkpY=,tag:BN8RRrAVzNMwRSIxl7L62w==,type:str]
type: ENC[AES256_GCM,data:JGbg36Dc,iv:f0yxuLu6bMVBVoe2m956gg5IRIpoov52buIuVr24NhA=,tag:noe6CKBg1GyVrYqM5F+/3w==,type:str]
stringData:
    github_token: ENC[AES256_GCM,data:jOe4GvKH5UK5xWCaUukw6MdH9yAy8DeI551hOSaUoyBmU3dGyEcwmw==,iv:bwFj2VsSaMivQsm4Ri48ps8CwD3Csxm5Mmom3RnGitw=,tag:nSIVdVtMvP02lawa1TArbQ==,type:str]
sops:
    age:
        - recipient: age1asrypfk4rkp8fkldqkrp6snhcxmanwtykc8xtzhd4n43f7zzkppst934ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXRJTUpuS21rQ1NHVXRo
            UTNSN2RKenB4cUNXSGlrRW16QTFVMGMzQjIwCi8zOE1kaUV6eEJDODk0dG0za2o0
            TkVIdTBQUkh5Qmx3NWtCRitTUDdOeW8KLS0tIHRkb3g0R01HUVNJWU1UbW84NlNv
            YmdiR2oxaHZsS0JrWHZBRGNZWjRHaTgKe6b5FcYvheU39p5IOP3J83sAdXi2U13r
            YMvBXJaHAvVd51eCdyyTNLvbKLmKiBff7HmEWla1o2ducHX7n4nktw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T01:22:40Z"
    mac: ENC[AES256_GCM,data:NrcboHCF7snmdlnzQtdxDmJ5bCipyMo1MQhHqje6VIjhcdH0LukWqKTV5WHDLIVwjkTScHsK+fuu2KKeH4Bf9+Gq/1qQcX7twbwmyOesxzY6G+ZkNzdwDZI3W4NrJVzUieIg/VlXDIZPpKmlgbXIcZJyc1raiq9LAstFd1kLZF4=,iv:NlcZiobwIKRVqgNT/n0R1B8yb1oVJ3Eh8m7ai7EO+ww=,tag:Y/2aspwyQ+/5VBKABHcjoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
