apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      chart: metrics-server
      version: 3.12.2
      interval: 30m
  values:
    args:
    - --kubelet-insecure-tls
