apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      version: '3.12.2'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 1m0s
  releaseName: metrics-server
  targetNamespace: kube-system
  values:
    args:
      - --kubelet-insecure-tls
