apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: akri
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/core/akri
  interval: 10m
  prune: true
  dependsOn:
  - name: cilium
