apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/networking/cilium
  interval: 10m
  prune: true
  dependsOn:
    - name: gateway-api
