apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/core/cloudnative-pg
  interval: 10m
  prune: true
  dependsOn:
  - name: openebs
