apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/networking/external-dns
  interval: 10m
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: coredns
