apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/external-dns
  interval: 10m
  prune: true
  dependsOn:
  - name: cilium
  - name: coredns
  # TODO: remove
  suspend: true
