apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/core/external-secrets
  interval: 10m
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
