apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateways
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/networking/gateways
  interval: 10m
  prune: true
  dependsOn:
  - name: gateway-api
