apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/apps/home-assistant
  interval: 10m
  prune: true
