apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/monitoring/metrics-server
  interval: 10m
  prune: true
