apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/networking/multus
  interval: 10m
  prune: true
  dependsOn:
  - name: cilium
