apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-chart
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/openebs/chart
  interval: 10m
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs-crds
spec:
  dependsOn:
    - name: openebs-chart
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/openebs/crds
  interval: 10m
  prune: true
