apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/core/openebs
  interval: 10m
  prune: true
