apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-secrets
spec:
  interval: 30m
  url: https://github.com/external-secrets/external-secrets
  ref:
    tag: v0.20.3
