apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cilium
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    k8sServiceHost: knecht
    k8sServicePort: 6443
    kubeProxyReplacement: true
    rollOutCiliumPods: true
    gatewayAPI:
      enabled: true
    ipam:
      mode: kubernetes
      operator:
        clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    envoy:
      rollOutPods: true
    operator:
      replicas: 1
      rollOutPods: true
    k8sClientRateLimit:
      qps: 50
      burst: 200
