apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: kube-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./deploy/cilium
  interval: 10m
  timeout: 1m
  prune: true
  wait: false
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cilium-operator
    namespace: kube-system
