apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: cilium-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: http-listener
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: All
