apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    releaseName: cilium
    namespace: kube-system
    version: 1.17.4
    valuesInline:
      "bpf":
        "masquerade": true
      "cgroup":
        "autoMount":
          "enabled": false
        "hostRoot": "/sys/fs/cgroup"
      "gatewayAPI":
        "enableAlpn": true
        "enableAppProtocol": true
        "enabled": true
      "hubble":
        "relay":
          "enabled": true
        "ui":
          "enabled": true
      "ipam":
        "mode": "kubernetes"
      "k8sServiceHost": "localhost"
      "k8sServicePort": 6443
      "kubeProxyReplacement": true
      "l2announcements":
        "enabled": true
      "operator":
        "replicas": 1
      "securityContext":
        "capabilities":
          "ciliumAgent":
            - "CHOWN"
            - "KILL"
            - "NET_ADMIN"
            - "NET_RAW"
            - "IPC_LOCK"
            - "SYS_ADMIN"
            - "SYS_RESOURCE"
            - "DAC_OVERRIDE"
            - "FOWNER"
            - "SETGID"
            - "SETUID"
          "cleanCiliumState":
            - "NET_ADMIN"
            - "SYS_ADMIN"
            - "SYS_RESOURCE"