apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# noinspection KubernetesUnknownValues
resources:
- bgp-advertisement.yaml
- bgp-cluster-config.yaml
- bgp-peer-config.yaml
- node-config.yaml
- pod-ip-pool.yaml
- release.yaml
- repository.yaml
