name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      spec:
        required: true
      run_name:
        required: false

run-name: '${{ github.event.inputs.run_name }}'

jobs:
  digger-job:
    #runs-on: ubuntu-24.04
    runs-on: arc-runner-set-test

    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - run: echo "job id ${{ fromJSON(inputs.spec).job_id }}"
      - run: |
          mkdir -p /usr/local/bin
          curl -fsSL "https://github.com/tofuutils/tenv/releases/download/v4.7.21/tenv_v4.7.21_Linux_x86_64.tar.gz" \
            | tar xzf - -C /usr/local/bin
      - uses: diggerhq/digger@56fcfdad089792f88db7de27e8ea91da9723a420 # v0.6.136
        with:
          digger-spec: ${{ inputs.spec }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
