name: Lint

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  pr_title:
    name: PR Title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: karancode/yamllint-github-action@v3.0.0
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
