name: pre-commit

on:
  pull_request:

jobs:
  get-hooks:
    runs-on: ubuntu-24.04
    name: "Get hooks"
    outputs:
      ids: ${{ steps.hooks.outputs.ids }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
      - id: hooks
        run: |
          hooks="$(yq -o=json -I=0 '[.repos[].hooks[].id]' .pre-commit-config.yaml)"
          echo "ids=${hooks}" >> $GITHUB_OUTPUT

  hook:
    runs-on: ubuntu-24.04
    name: "Hook: ${{ matrix.hook }}"
    needs: get-hooks
    env:
      TENV_AUTO_INSTALL: true
    strategy:
      fail-fast: false
      matrix:
        hook: ${{ fromJSON(needs.get-hooks.outputs.ids) }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
        with:
          repo: tofuutils/tenv
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: .python-version
      - uses: 1password/load-secrets-action/configure@8d0d610af187e78a2772c2d18d627f4c52d3fbfb # v3.1.0
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - uses: 1password/load-secrets-action@vzt/prepare-relese-v3.1.0
        with:
          export-env: true
        env:
          OP_ENV_FILE: .openv
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: ${{ matrix.hook }}
