name: pre-commit

on:
  pull_request:

jobs:
  get-hooks:
    runs-on: ubuntu-24.04
    name: "Get hooks"
    outputs:
      ids: ${{ steps.hooks.outputs.ids }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
      - id: hooks
        run: |
          hooks="$(yq -o=json -I=0 '[.repos[].hooks[].id]' .pre-commit-config.yaml)"
          echo "ids=${hooks}" >> $GITHUB_OUTPUT

  hook:
    runs-on: ubuntu-24.04
    name: "Hook: ${{ matrix.hook }}"
    needs: get-hooks
    # TODO: think about where to place this
    env:
      PROXMOX_VE_INSECURE: true
    strategy:
      fail-fast: false
      matrix:
        hook: ${{ fromJSON(needs.get-hooks.outputs.ids) }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: versions
        run: |
          echo "terragrunt=$(cat .terragrunt-version)" >> $GITHUB_OUTPUT
          echo "tofu=$(cat .opentofu-version)" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - uses: gruntwork-io/terragrunt-action@95fc057922e3c3d4cc021a81a213f088f333ddef # v3.0.2
        with:
          tg_version: ${{ steps.versions.outputs.terragrunt }}
          tofu_version: ${{ steps.versions.outputs.tofu }}
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      - uses: 1password/load-secrets-action/configure@13f58eec611f8e5db52ec16247f58c508398f3e6 # v3.0.0
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - uses: 1password/load-secrets-action@vzt/prepare-relese-v3.1.0
        with:
          export-env: true
        env:
          OP_ENV_FILE: op.env
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: ${{ matrix.hook }} --all-files
